### ISSUE TITLE
Add a readme

### ISSUE THREAD

**Issue by Zauberfisch** [wolfv/uberwriter#2]
add a readme file containing the contents of or linking directly to http://uberwriter.wolfvollprecht.de/

**Comment by fedelibre** [comment]
The readme was added with commit 19f936d

That website seems mainly for ubuntu users..
People interested in contributing should scroll down to the end of google results (currently) to find the github link. I used an old version  because I thought the source was hosted on launchpad...

**Comment by fedelibre** [comment]
What I'd rather write in the README is few simple instructions to install.

I've found these dependencies: ``python3-regex python3-distutils-extra python3-levenshtein``.
There are others maybe, I didn't check in a virtualenv.

Currently I can install with ``sudo python3 setup.py install --root=/``. See issue #4 .

**Comment by GKFX** [comment]
@fedelibre Could you add `python3-cairo` to your list? It's needed (and mentioned in https://github.com/wolfv/uberwriter/blob/master/debian/control).

**Comment by fedelibre** [comment]
@GKFX I've edited  my comment, thanks

**Comment by fedelibre** [comment]
BTW, the README now recommends installing dependencies with ``pip install -r requirements``, but:

- the file is actually named `requirements.txt`
- and it contains only `regex`

**Comment by jonalmeida** [comment]
@fedelibre You might be missing python3-apt from my findings. See my fork at [jonalmeida/UberWriter](https://github.com/jonalmeida/UberWriter) for reference.

**Comment by wolfv** [comment]
Hi guys, 

yep, all the installation stuff is a bit broken, sorry. I added your recommendations, thanks a lot. 

I just recently moved away from Ubuntu to Fedora. Also, several parts of UberWriter are currently a bit broken because I had too many good ideas to finish.

`python-apt` should only be available on Ubuntu (maybe debian) and derivatives. I think I encapsulated that in a try-block so it shouldn't be needed.

Wolf
